name: android

on:
  workflow_dispatch:
  push:
    paths:
      - 'lib/**.[ch]'
      - 'lib/**.cpp'
      - 'src/**.[ch]'
      - 'src/**.cpp'
      - 'irr/**.[ch]'
      - 'irr/**.cpp'
      - '**/CMakeLists.txt'
      - 'cmake/Modules/**'
      - 'po/**.po'
      - 'android/**'
      - '.github/workflows/android.yml'
  pull_request:
    paths:
      - 'lib/**.[ch]'
      - 'lib/**.cpp'
      - 'src/**.[ch]'
      - 'src/**.cpp'
      - 'irr/**.[ch]'
      - 'irr/**.cpp'
      - '**/CMakeLists.txt'
      - 'cmake/Modules/**'
      - 'po/**.po'
      - 'android/**'
      - '.github/workflows/android.yml'

jobs:
  build:
    runs-on: ubuntu-22.04
    steps:
    - uses: actions/checkout@v7
    - name: Install deps
      run: |
        sudo apt-get update
        sudo apt-get install -y --no-install-recommends gettext
    - name: Set up JDK 17
      uses: actions/setup-java@v5
      with:
          distribution: 'temurin'
          java-version: '17'
    - name: Download Mineclonia Game and Configure Gradle Injection
      run: |
        # 1. تحميل اللعبة في مجلد الألعاب الرئيسي للمستودع (الخيار الطبيعي للمحرك)
        git clone https://codeberg.org/Mineclonia/Mineclonia.git games/mineclonia
        
        # 2. تعيين اللعبة كافتراضية في ملف الإعدادات النموذجي ليتم اعتماده عند الإقلاع الأول
        echo "default_game = mineclonia" >> minetest.conf.example
        
        # 3. حقن كود رسمي في نهاية ملف الـ Gradle لإجبار المحرك على دمج وفهرسة مجلد الألعاب تلقائياً
        echo -e "\ntasks.named('copyAssets').configure {\n    from '../../games'\n    into 'src/main/assets/games'\n}" >> android/app/build.gradle
    - name: Build AAB with Gradle
      run: cd android; ./gradlew bundlerelease
    - name: Build APKs with Gradle
      run: cd android; ./gradlew assemblerelease
    - name: Save AAB artifact
      uses: actions/upload-artifact@v7
      with:
        name: Luanti-release.aab
        path: android/app/build/outputs/bundle/release/app-release.aab
    - name: Save armeabi artifact
      uses: actions/upload-artifact@v7
      with:
        name: Luanti-armeabi-v7a.apk
        path: android/app/build/outputs/apk/release/app-armeabi-v7a-release-unsigned.apk
    - name: Save arm64 artifact
      uses: actions/upload-artifact@v7
      with:
        name: Luanti-arm64-v8a.apk
        path: android/app/build/outputs/apk/release/app-arm64-v8a-release-unsigned.apk
    - name: Save x86 artifact
      uses: actions/upload-artifact@v7
      with:
        name: Luanti-x86.apk
        path: android/app/build/outputs/apk/release/app-x86-release-unsigned.apk
    - name: Save x86_64 artifact
      uses: actions/upload-artifact@v7
      with:
        name: Luanti-x86_64.apk
        path: android/app/build/outputs/apk/release/app-x86_64-release-unsigned.apk
